/* Generated by AN DISI Unibo */ 
package it.unibo.cargorobot

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024
import main.java.map.*

class Cargorobot ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "state_init"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		
					MapServiceSingleton.init("map.json");
					var idle = true
					var X:Int? = 0
					var Y:Int? = 0
					var Dir = ""
					var Map = MapServiceSingleton.getInstance()
					var Slot = ""
					var robotIsMoving = false
					
					var LastAttemptedState = ""  // for moverobotfailed
					
					//fixed coordinates
					var HomeLoc = Map.getCoordinates("Home");
					var Homecoords = HomeLoc.getCoords();
					var Home_X = Homecoords.get("x");
					var Home_Y = Homecoords.get("y");
					var Homedir = HomeLoc.getFacingDir()
					
					var PupLoc = Map.getCoordinates("Pickup");
					var Pupcoords = PupLoc.getCoords();
					var Pup_X = Pupcoords.get("x");
					var Pup_Y = Pupcoords.get("y");
					var Pupdir = PupLoc.getFacingDir()
		return { //this:ActionBasciFsm
				state("state_init") { //this:State
					action { //it:State
						discardMessages = false
						CommUtils.outblue("[CargoRobot] | Started ")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="state_engage", cond=doswitch() )
				}	 
				state("state_engage") { //this:State
					action { //it:State
						delay(3000) 
						CommUtils.outblue("[Cargorobot] | Requests engage to basicrobot, name: $MyName ")
						request("engage", "engage($MyName,330)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 interrupthandle(edgeName="t10",targetState="state_wait_resume",cond=whenEvent("stopActions"),interruptedStateTransitions)
					transition(edgeName="t11",targetState="state_idle",cond=whenReply("engagedone"))
					transition(edgeName="t12",targetState="state_engage",cond=whenReply("engagerefused"))
				}	 
				state("state_idle") { //this:State
					action { //it:State
						CommUtils.outblue("[Cargorobot] | Idle ")
						
									idle=true
									robotIsMoving = false
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 interrupthandle(edgeName="t03",targetState="state_wait_resume",cond=whenEvent("stopActions"),interruptedStateTransitions)
					transition(edgeName="t04",targetState="goto_IO_port",cond=whenRequest("loadcontainer"))
				}	 
				state("state_wait_resume") { //this:State
					action { //it:State
						CommUtils.outred("[Cargorobot] | Stops ")
						emit("alarm", "alarm(STOP)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t15",targetState="state_resume",cond=whenEvent("resumeActions"))
					transition(edgeName="t16",targetState="mexEater",cond=whenReply("moverobotdone"))
					transition(edgeName="t17",targetState="mexEater",cond=whenReply("moverobotfailed"))
				}	 
				state("mexEater") { //this:State
					action { //it:State
						CommUtils.outcyan("[Cargorobot] | Consuming message while stopped ")
						forward("resume", "resume(consumed)" ,name ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t18",targetState="state_resume",cond=whenEvent("resumeActions"))
				}	 
				state("handle_move_failure") { //this:State
					action { //it:State
						CommUtils.outred("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						CommUtils.outblack("[Cargorobot] | Movement failed! Waiting 5 seconds before retry.")
						delay(5000) 
						forward("resume", "resume(goon)" ,"cargorobot" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t09",targetState="goto_IO_port",cond=whenDispatchGuarded("resume",{ LastAttemptedState == "goto_IO_port"  
					}))
					transition(edgeName="t010",targetState="goto_IO_port",cond=whenDispatchGuarded("resume",{ LastAttemptedState == "state_move_cont"  
					}))
					transition(edgeName="t011",targetState="returnHOME",cond=whenDispatchGuarded("resume",{ LastAttemptedState == "returnHOME"  
					}))
				}	 
				state("state_resume") { //this:State
					action { //it:State
						CommUtils.outred("[Cagorobot] | Resume ")
						if( robotIsMoving 
						 ){request("moverobot", "moverobot($X,$Y)" ,"basicrobot" )  
						CommUtils.outyellow("[Cagorobot] | Resuming movement to X:$X, Y:$Y ")
						}
						returnFromInterrupt(interruptedStateTransitions)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("state_move_cont") { //this:State
					action { //it:State
						
									LastAttemptedState = "state_move_cont"
									var location = Map.getCoordinates(Slot);
									var coords = location.getCoords();
									X = coords.get("x");
									Y = coords.get("y");
									Dir=location.getFacingDir();
						CommUtils.outblue("[Cargorobot] Moving container to slot $Slot... X:$X, Y:$Y")
						robotIsMoving = true 
						request("moverobot", "moverobot($X,$Y)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t312",targetState="at_slot",cond=whenReply("moverobotdone"))
					transition(edgeName="t313",targetState="handle_move_failure",cond=whenReply("moverobotfailed"))
				}	 
				state("at_slot") { //this:State
					action { //it:State
						CommUtils.outgreen("[cargorobot] arrived at slot, dir:$Dir")
						robotIsMoving = false 
						forward("setdirection", "dir($Dir)" ,"basicrobot" ) 
						delay(2000) 
						forward("resume", "resume(at_slot)" ,name ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 interrupthandle(edgeName="t014",targetState="state_wait_resume",cond=whenEvent("stopActions"),interruptedStateTransitions)
					transition(edgeName="t015",targetState="state_finalize",cond=whenDispatch("resume"))
				}	 
				state("returnHOME") { //this:State
					action { //it:State
						CommUtils.outblue("Cargorobot | returningHome, state: $idle")
						 
									LastAttemptedState = "returnHOME"
									X = Home_X
									Y = Home_Y
									Dir = Homedir
									robotIsMoving=true
						CommUtils.outmagenta("Cargorobot | returningHome, X:$X  Y: $Y ")
						request("moverobot", "moverobot($X,$Y)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 interrupthandle(edgeName="t016",targetState="state_wait_resume",cond=whenEvent("stopActions"),interruptedStateTransitions)
					transition(edgeName="t017",targetState="at_HOME",cond=whenReply("moverobotdone"))
					transition(edgeName="t018",targetState="handle_move_failure",cond=whenReply("moverobotfailed"))
				}	 
				state("at_HOME") { //this:State
					action { //it:State
						robotIsMoving=false 
						forward("setdirection", "dir($Dir)" ,"basicrobot" ) 
						CommUtils.outgreen("[cargorobot] arrived at home, dir: $Dir")
						forward("resume", "resume(at_home)" ,name ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 interrupthandle(edgeName="t019",targetState="state_wait_resume",cond=whenEvent("stopActions"),interruptedStateTransitions)
					transition(edgeName="t020",targetState="state_idle",cond=whenDispatchGuarded("resume",{idle 
					}))
					transition(edgeName="t021",targetState="goto_IO_port",cond=whenDispatchGuarded("resume",{!idle 
					}))
				}	 
				state("goto_IO_port") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("loadcontainer(Slot)"), Term.createTerm("loadcontainer(Slot)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 Slot = payloadArg(0)  
						}
						CommUtils.outblue("Cargorobot | go to IOport")
						 
									LastAttemptedState = "goto_IO_port"
									X = Pup_X
									Y = Pup_Y
									Dir = Pupdir
									idle=false 
									robotIsMoving = true
						request("moverobot", "moverobot($X,$Y)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 interrupthandle(edgeName="t022",targetState="state_wait_resume",cond=whenEvent("stopActions"),interruptedStateTransitions)
					transition(edgeName="t023",targetState="at_IO_port",cond=whenReply("moverobotdone"))
					transition(edgeName="t024",targetState="handle_move_failure",cond=whenReply("moverobotfailed"))
				}	 
				state("at_IO_port") { //this:State
					action { //it:State
						CommUtils.outgreen("[cargorobot] arrived at ioport, dir: $Dir")
						robotIsMoving=false 
						forward("setdirection", "dir($Dir)" ,"basicrobot" ) 
						forward("resume", "resume(at_ioport)" ,name ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 interrupthandle(edgeName="t025",targetState="state_wait_resume",cond=whenEvent("stopActions"),interruptedStateTransitions)
					transition(edgeName="t026",targetState="state_move_cont",cond=whenDispatch("resume"))
				}	 
				state("state_finalize") { //this:State
					action { //it:State
						answer("loadcontainer", "containerloaded", "containerloaded(YEE)"   )  
						CommUtils.outyellow("[cargorobot] inviata reply containerloaded")
						
									idle = true
									robotIsMoving=false
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="returnHOME", cond=doswitch() )
				}	 
			}
		}
} 
