/* Generated by AN DISI Unibo */ 
package it.unibo.sonarsimul

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Sonarsimul ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		
				var count=0
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						delay(15000) 
						CommUtils.outmagenta("sonarsimul | AVVIATO")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("work") { //this:State
					action { //it:State
						CommUtils.outmagenta("sonarsimul | Emetto 25 (per causare FAULT)")
						emitLocalStreamEvent("sonardata", "distance(25)" ) 
						delay(1000) 
						emitLocalStreamEvent("sonardata", "distance(26)" ) 
						delay(1000) 
						emitLocalStreamEvent("sonardata", "distance(25)" ) 
						delay(2000) 
						CommUtils.outmagenta("sonarsimul | Emetto 8 (per causare RESUME)")
						emitLocalStreamEvent("sonardata", "distance(8)" ) 
						delay(1000) 
						emitLocalStreamEvent("sonardata", "distance(15)" ) 
						delay(1000) 
						emitLocalStreamEvent("sonardata", "distance(5)" ) 
						delay(2000) 
						CommUtils.outmagenta("sonarsimul | Emetto 8 (per causare containerhere)")
						emitLocalStreamEvent("sonardata", "distance(8)" ) 
						delay(1000) 
						emitLocalStreamEvent("sonardata", "distance(7)" ) 
						delay(1000) 
						emitLocalStreamEvent("sonardata", "distance(9)" ) 
						delay(20000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="error_and_resume", cond=doswitch() )
				}	 
				state("error_and_resume") { //this:State
					action { //it:State
						if( count % 2 == 0 
						 ){CommUtils.outmagenta("sonarsimul | Emetto 25 (per causare FAULT)")
						emitLocalStreamEvent("sonardata", "distance(25)" ) 
						delay(1000) 
						emitLocalStreamEvent("sonardata", "distance(26)" ) 
						delay(1000) 
						emitLocalStreamEvent("sonardata", "distance(25)" ) 
						delay(3000) 
						CommUtils.outmagenta("sonarsimul | Emetto 8 (per causare RESUME)")
						emitLocalStreamEvent("sonardata", "distance(8)" ) 
						delay(1000) 
						emitLocalStreamEvent("sonardata", "distance(15)" ) 
						delay(1000) 
						emitLocalStreamEvent("sonardata", "distance(5)" ) 
						delay(20000) 
						}
						count++ 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
			}
		}
} 
