const { MongoClient } = require('mongodb');

async function main() {
  const uri = 'mongodb://localhost:27017'; 

  const client = new MongoClient(uri);

  try {
    // Connessione al server MongoDB
    await client.connect();
    console.log('✅ Connesso a MongoDB');

    // Seleziona (o crea) il database
    const db = client.db('cargodb');

    // Crea (o accede) alla collection
    const collection = db.collection('products');


    // _id will be automatically generated by MongoDB if not provided.
    const documentsToInsert = [
      {
        productId: 20,
        jsonRep: "{\"productId\":20,\"name\":\"p20\",\"weight\":200}"
      },
      {
        productId: 21,
        jsonRep: "{\"productId\":21,\"name\":\"p21\",\"weight\":210}"
      },
      {
        productId: 22,
        jsonRep: "{\"productId\":22,\"name\":\"p22\",\"weight\":220}"
      },
      {
        productId: 23,
        jsonRep: "{\"productId\":23,\"name\":\"p23\",\"weight\":230}"
      },
      {
        productId: 17,
        jsonRep: "{\"productId\":17,\"name\":\"p17\",\"weight\":170}"
      },
      {
        productId: 1,
        jsonRep: "{\"productId\":1,\"name\":\"p1\",\"weight\":1}"
      }
    ];

    // Inserisce tutti i documenti nell'array
    // insertMany() ritorna un oggetto con insertedCount e insertedIds
    const result = await collection.insertMany(documentsToInsert);
    console.log(`📦 Inseriti ${result.insertedCount} documenti.`);
    console.log("ID dei documenti inseriti:");
    // Itera sugli ID inseriti per stamparli
    for (const key in result.insertedIds) {
      console.log(`  - ${result.insertedIds[key]}`);
    }
  } catch (err) {
    console.error('❌ Errore:', err);
  } finally {
    // Chiudi la connessione
    await client.close();
    console.log('🔌 Connessione chiusa');
  }
}

main();
