/* Generated by AN DISI Unibo */ 
package it.unibo.gui_state_observer

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024
import main.java.unibo.disi.cargoservicestatusgui.ws.WebSocketHandler

class Gui_state_observer ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outgreen("$name | Avvio e inizio ad osservare cargoservice...")
						observeResource("cargoservicecore","8000","ctx_cargoservice","cargoservice","hold_state_update")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="push_state_to_gui",cond=whenDispatch("hold_state_update"))
				}	 
				state("push_state_to_gui") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("update(JSONSTATE)"), Term.createTerm("update(JSONSTATE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												val holdStateJson = payloadArg(0)
												// Invia il JSON a tutti i client web tramite il Manager condiviso.
												WebSocketHandler.getInstance().sendToAll(holdStateJson)
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t01",targetState="push_state_to_gui",cond=whenDispatch("hold_state_update"))
				}	 
			}
		}
} 
